# Generated by Django 5.1.4 on 2025-04-08 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_blogcategory_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcategory',
            name='code',
            field=models.CharField(max_length=50),
        ),
    ]
